name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Runner check
        run: hostname

      - name: Deploy devnext
        run: sudo systemctl start devnext-deploy.service